language: ruby
cache: bundler
rvm:
- 2.2.1
before_script:
  - bundle exec rake db:setup
script:
  - bundle exec rspec
  - bundle exec cucumber
deploy:
  provider: heroku
  api_key:
    secure: "YOUR ENCRYPTED API KEY"
